[env:native]
platform = native
test_framework = unity
lib_deps = fire_control_sources

build_flags =
  -std=c++11
  -include Arduino.h
  -I stubs
  -I /Users/amp/Dropbox/Arduino/HMTL_Ecosystem/HMTL/platformio/HMTL_Test/stubs
  -I ../../HMTL_Fire_Control_Wickerman
  -I /Users/amp/Dropbox/Arduino/HMTL_Ecosystem/HMTL/Libraries/HMTLTypes
  -I /Users/amp/Dropbox/Arduino/HMTL_Ecosystem/HMTL/Libraries/HMTLMessaging
  -I /Users/amp/Dropbox/Arduino/HMTL_Ecosystem/HMTL/Libraries/HMTLPoofer
  -I /Users/amp/Dropbox/Arduino/libraries/Socket
  -DDISABLE_RS485
  -DDISABLE_MPR121
  -DDISABLE_XBEE
  -DDEBUG_LEVEL=5
  -DOBJECT_TYPE=5
  -DCONTROL_MODE=4
  -DPOOFER1_ADDRESS=66
  -DPOOFER2_ADDRESS=69
  -DLIGHTS_ADDRESS=67
